SOneApprendaHelper/Controllers/GuidesController.cs
using System.Web.Mvc;
using SOneApprendaHelper.Models;
using SOneApprendaHelper.Services;

namespace SOneApprendaHelper.Controllers
{
    public class GuidesController : Controller
    {
        private readonly ICookiesService _cookiesService;

        public GuidesController(ICookiesService cookiesService)
        {
            _cookiesService = cookiesService;
        }

        [HttpGet]
        public ActionResult Index()
        {
            var settings = _cookiesService.Get<ApprendaSettings>(
                ControllerContext.HttpContext.Request.Cookies, ApprendaSettings.SETTINGS_KEY);

            return View(settings);
        }
    }
}

SOneApprendaHelper/Controllers/LinksController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Newtonsoft.Json;
using SOneApprendaHelper.Models;
using SOneApprendaHelper.Services;

namespace SOneApprendaHelper.Controllers
{
    public class LinksController : Controller
    {
        private readonly ICookiesService _cookiesService;
        private readonly IApprendaLinksGenerator _apprendaLinksGenerator;

        public LinksController(ICookiesService cookiesService, IApprendaLinksGenerator apprendaLinksGenerator)
        {
            _cookiesService = cookiesService;
            _apprendaLinksGenerator = apprendaLinksGenerator;
        }

        [HttpGet]
        public ActionResult List()
        {
            return View(getLinks());
        }

        [HttpGet]
        public ContentResult JsonList()
        {
            var links = getLinks();
            var json = JsonConvert.SerializeObject(links);

            return Content(json, "text/json");
        }

        [HttpGet]
        public ActionResult Navigate(string id)
        {
            var settings = _cookiesService.Get<ApprendaSettings>(
                 ControllerContext.HttpContext.Request.Cookies, ApprendaSettings.SETTINGS_KEY);

            if (settings == null)
                return RedirectToAction("List");

            var url = _apprendaLinksGenerator.GenerateApprendaUrl(id, settings);
            if (url == null)
                return RedirectToAction("List");

            return Redirect(url);
        }

        private IEnumerable<ApprendaLink> getLinks()
        {
            var settings = _cookiesService.Get<ApprendaSettings>(
                ControllerContext.HttpContext.Request.Cookies, ApprendaSettings.SETTINGS_KEY);

            if (settings == null)
                return null;

            var links = _apprendaLinksGenerator.GenerateApprendaLinks(settings).ToList();
            links.Sort(ApprendaLink.NameComparer);

            return links;
        }
    }
}

SOneApprendaHelper/Controllers/SettingsController.cs
using System;
using System.Web.Mvc;
using SOneApprendaHelper.Models;
using SOneApprendaHelper.Services;

namespace SOneApprendaHelper.Controllers
{
    public class SettingsController : Controller
    {
        private readonly ICookiesService _cookiesService;

        public SettingsController(ICookiesService cookiesService)
        {
            _cookiesService = cookiesService;
        }

        [HttpGet]
        public ActionResult Edit()
        {
            var settings = _cookiesService.Get<ApprendaSettings>(
                ControllerContext.HttpContext.Request.Cookies, ApprendaSettings.SETTINGS_KEY) ?? new ApprendaSettings();

            return View(settings);
        }

        [HttpPost]
        public ActionResult Edit(ApprendaSettings settings)
        {
            if (ModelState.IsValid)
            {
                _cookiesService.Set(
                    ControllerContext.HttpContext.Response.Cookies,
                    ApprendaSettings.SETTINGS_KEY,
                    settings,
                    DateTime.MaxValue);

                ViewBag.AlertMessage = "Apprenda Settings have been saved successfully.";
            }

            return View();
        }
    }
}

SOneApprendaHelper/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - SOne Apprenda Helper</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("SOne Apprenda Helper", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="@Url.Action("Index", "Home")"><span class="glyphicon glyphicon-home"></span></a></li>
                <li><a href="@Url.Action("Index", "Guides")"><span class="glyphicon glyphicon-book"></span></a></li>
                <li><a href="@Url.Action("List", "Links")"><span class="glyphicon glyphicon-random"></span></a></li>
                <li><a href="@Url.Action("Edit", "Settings")"><span class="glyphicon glyphicon-cog"></span></a></li>
            </ul>
        </div>
    </div>
</div>
<div class="container body-content">
    @RenderBody()
</div>

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
@RenderSection("scripts", required: false)
</body>
</html>